name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

environment:
  name: Production
  url: ${{ steps.deploy.outputs.firebase_url }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
      
      - name: Build React app using Vite
        run: npm run build
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        run: |
          DEPLOY_OUTPUT=$(firebase deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }})
          echo "$DEPLOY_OUTPUT"
          FIREBASE_URL=$(echo "$DEPLOY_OUTPUT" | grep "Hosting URL:" | cut -d' ' -f3)
          echo "firebase_url=$FIREBASE_URL" >> $GITHUB_OUTPUT
